version: '3.7'
services:

  bk-register:
    image: waggle/beekeeper-register
    build: bk-register
    restart: always
    depends_on:
      - bk-api
    init: true
    ports:
      - "127.0.0.1:24181:80"
    environment:
      KEY_GEN_TYPE: ${KEY_GEN_TYPE}
      KEY_GEN_ARGS: ${KEY_GEN_ARGS}
      # see .env
    volumes:
      - "bk-secrets:/usr/lib/waggle/:ro"
      - ${PWD}/bk-register/ROOTFS/opt/sage/beekeeper/register:/opt/sage/beekeeper/register

  bk-sshd:
    image: waggle/beekeeper-sshd
    build: bk-sshd
    restart: always
    depends_on:
      - bk-register
    ports:
      - "127.0.0.1:20022:22"
      - "127.0.0.1:24182:80"
    environment:
        # e.g. SSHD_FLAGS="-ddd"
      SSHD_FLAGS: ""
      KEY_GEN_TYPE: ${KEY_GEN_TYPE}
      KEY_GEN_ARGS: ${KEY_GEN_ARGS}
      USE_CONFIG_VOLUME: ${USE_CONFIG_VOLUME}
      # see .env
    volumes:
      - "bk-secrets:/usr/lib/waggle/:rw"

  bk-api:
    image: waggle/beekeeper-api
    build: bk-api
    restart: always
    depends_on:
      - db
    env_file: mysql.env
    volumes:
      - ${PWD}/bk-api:/usr/src/app
    ports:
      - "5000:5000"  # for testing purposes
    #environment:
    #  FLASK_APP: bk-api.py
    #  FLASK_ENV: production


  db:
    image: mysql:8.0.20
    env_file: mysql.env
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - beekeeper-db:/var/lib/mysql

volumes:
  #bk-homedirs:
  beekeeper-db:
  bk-secrets:
  #  external:
  #    name: beekeeper-config_bk-secrets

