version: '3.7'
services:

  bk-register:
    build: bk-register
    restart: always
    init: true
    ports:
      - "127.0.0.1:24181:80"
    volumes:
      - "bk-secrets:/usr/lib/sage/:ro"

  bk-sshd:
    build: bk-sshd
    restart: always
    depends_on:
      - bk-register
    ports:
      - "20022:22"
      - "127.0.0.1:24182:80"
    volumes:
      - "bk-homedirs:/home_dirs"
      - "bk-secrets:/usr/lib/sage/:ro"

  bk-nodes:
    image: beekeeper/bk-nodes
    build: bk-nodes
    restart: always
    env_file: mysql.env
    volumes:
      - ${PWD}/bk-nodes:/usr/src/app
    ports:
      - "5000:5000"  # for testing purposes
    #environment:
    #  FLASK_APP: bk-nodes.py
    #  FLASK_ENV: production


  db:
    image: mysql:8.0.20
    env_file: mysql.env
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/init.sql
      #- beekeeper-db:/var/lib/mysql

volumes:
  bk-homedirs:
  bk-secrets:
    external:
      name: beekeeper-config_bk-secrets

