apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beekeeper-sshd-pvc
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #hostPath:
  #  path: "/mnt/data"

