apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: beekeeper-api
  name: beekeeper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: beekeeper-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: beekeeper-api
    spec:
      containers:
      - image: waggle/beekeeper-api:latest
        name: beekeeper-api
        volumeMounts:
          - name: ca-secret
            mountPath: "/usr/lib/waggle/certca/"
            readOnly: true
          - name: nodes-secret
            mountPath: "/config/nodes/nodes.pem"
            subPath: nodes.pem
            readOnly: true
          - name: admin-key
            mountPath: /config/admin-key/admin.pem
            subPath: admin.pem
            readOnly: true
        envFrom:
          - configMapRef:
              name: beekeeper-api-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beekeeper-api-secret
              key: MYSQL_PASSWORD

        - name: KEY_GEN_TYPE
          valueFrom:
            configMapKeyRef:
              name: beekeeper-config
              key: KEY_GEN_TYPE
        - name: KEY_GEN_ARGS
          valueFrom:
            configMapKeyRef:
              name: beekeeper-config
              key: KEY_GEN_ARGS


        ports:
          - name: api
            containerPort: 5000

      volumes:
      - name: ca-secret
        secret:
          secretName: beekeeper-sshd-ca-secret
          defaultMode: 0400
      - name: nodes-secret
        secret:
          secretName: beekeeper-api-nodes-secret
          defaultMode: 0400
      - name: admin-key
        secret:
          defaultMode: 0400
          secretName: beekeeper-sshd-authorized-keys-secret

      restartPolicy: Always
