apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # beekeeper global config
  - beekeeper.configmap.yaml

  ### beekeeper API
  - beekeeper-api.configmap.yaml
  - beekeeper-api.deployment.yaml
  #- beekeeper-api.secret.yaml
  - beekeeper-api.service.yaml
  - beekeeper-api.ingress.yaml

  ### beekeeper sshd
  - beekeeper-sshd.deployment.yaml
  - beekeeper-sshd.configmap.yaml
  - beekeeper-sshd.service.yaml
  - beekeeper-sshd-pubreg.secret.yaml

