apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: beekeeper-register
  name: beekeeper-register
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: beekeeper-register
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: beekeeper-register
    spec:
      containers:
      - image: waggle/beekeeper-register:latest
        name: beekeeper-register
        volumeMounts:
          - name: ca-secret
            mountPath: "/usr/lib/waggle/certca/"
            readOnly: true
        env:
        - name: KEY_GEN_ARGS
          valueFrom:
            configMapKeyRef:
              name: beekeeper-config
              key: KEY_GEN_ARGS

        - name: BEEKEEPER_SSHD_API
          valueFrom:
            configMapKeyRef:
              name: beekeeper-register-config
              key: BEEKEEPER_SSHD_API
        - name: BEEKEEPER_DB_API
          valueFrom:
            configMapKeyRef:
              name: beekeeper-register-config
              key: BEEKEEPER_DB_API


        ports:
          - name: api
            containerPort: 80
      volumes:
      - name: ca-secret
        secret:
          secretName: beekeeper-sshd-ca-secret
          defaultMode: 0400
      restartPolicy: Always
