apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: beekeeper-api
  name: beekeeper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: beekeeper-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: beekeeper-api
    spec:
      containers:
      - image: waggle/beekeeper-api:latest
        name: beekeeper-api
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: beekeeper-api-config
              key: MYSQL_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: beekeeper-api-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: beekeeper-api-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beekeeper-api-secret
              key: MYSQL_PASSWORD

        ports:
          - name: api
            containerPort: 5000

      restartPolicy: Always
