apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: beekeeper-sshd
  name: beekeeper-sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: beekeeper-sshd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: beekeeper-sshd
    spec:
      containers:
      - image: waggle/beekeeper-sshd:latest
        name: beekeeper-sshd
        volumeMounts:
          - mountPath: /usr/lib/waggle/
            name: beekeeper-sshd
        env:
        - name: SSHD_FLAGS
          valueFrom:
            configMapKeyRef:
              name: beekeeper-sshd-config
              key: SSHD_FLAGS
        - name: BEEKEEPER_REGISTER_API
          valueFrom:
            configMapKeyRef:
              name: beekeeper-sshd-config
              key: BEEKEEPER_REGISTER_API
        - name: BEEKEEPER_DB_API
          valueFrom:
            configMapKeyRef:
              name: beekeeper-sshd-config
              key: BEEKEEPER_DB_API


        ports:
          - name: api
            containerPort: 80
          - name: ssh
            containerPort: 22

      restartPolicy: Always
      volumes:
      - name: beekeeper-sshd
        persistentVolumeClaim:
          claimName: beekeeper-sshd-pvc