apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # beekeeper global config
  - beekeeper.configmap.yaml

  ### beekeeper API
  #- beekeeper-api.configmap.yaml # This ConfigMaps has to be created after the first start of sshd
  - beekeeper-api.deployment.yaml
  - beekeeper-api.secret.yaml
  - beekeeper-api.service.yaml
  - beekeeper-api.ingress.yaml

  ### beekeeper register
  - beekeeper-register.deployment.yaml
  - beekeeper-register.configmap.yaml
  - beekeeper-register.service.yaml

  ### beekeeper sshd
  - beekeeper-sshd.deployment.yaml
  - beekeeper-sshd.configmap.yaml
  - beekeeper-sshd.service.yaml
  - beekeeper-sshd-pubreg.secret.yaml

