
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base" # relative path to the base folder

# example to specify different image tag
images:
  - name: waggle/beekeeper-sshd
    newTag: latest
  - name: waggle/beekeeper-api
    newTag: develop


resources:
  - beekeeper-api.secret.yaml

# Use patchesStrategicMerge to overwrite config
#patchesStrategicMerge:

  #- beekeeper-api.ingress.yaml
  #- beekeeper-sshd.service.yaml


#configMapGenerator: use secret instead!
#  - name: beekeeper-sshd-authorized-keys-config
#    files:
#      - admin.pem.pub
